# Generated by Django 5.0.1 on 2024-03-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last',
        ),
    ]
